[workspace]
name = "TauDEM"
version = "5.3.9"
description = "TauDEM (Terrain Analysis Using Digital Elevation Models)"
authors = ["David Tarboton <dtarb@usu.edu", "Valdenor Nilo de C. Jr. <nilocj@outlook.com"]
platforms = ["linux-64", "win-64"]
preview = ["pixi-build"]
channels = [
  "https://prefix.dev/conda-forge",
  "https://prefix.dev/pixi-build-backends",
]

[package]
name = "taudem"
version = "5.3.9"
description = "TauDEM (Terrain Analysis Using Digital Elevation Models)"

[package.build.backend]
name = "pixi-build-cmake"
version = "*"

[package.host-dependencies]
cmake = "*"

[package.build-dependencies]
libgdal = ">=3.9.3"
proj = ">=9.6.1"
cxx-compiler = ">=1.11.0,<2"

[target.linux-64.dependencies]
mpich-mpicxx = ">=4.2.3"
mpich = ">=4.2.3"

[target.win-64.dependencies]
msmpi = ">=10.1.1,<11"

[target.win-64.activation]
scripts = ["setvars.bat"]
